package tablas;
// Generated 14/05/2014 01:19:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private Integer codAlmacen;
     private String almacen;
     private String direccion;
     private String detalle;
     private String registro;
     private Set<CompraDetalle> compraDetalles = new HashSet<CompraDetalle>(0);
     private Set<KardexArticuloProducto> kardexArticuloProductos = new HashSet<KardexArticuloProducto>(0);

    public Almacen() {
    }

	
    public Almacen(String almacen, String direccion, String detalle, String registro) {
        this.almacen = almacen;
        this.direccion = direccion;
        this.detalle = detalle;
        this.registro = registro;
    }
    public Almacen(String almacen, String direccion, String detalle, String registro, Set<CompraDetalle> compraDetalles, Set<KardexArticuloProducto> kardexArticuloProductos) {
       this.almacen = almacen;
       this.direccion = direccion;
       this.detalle = detalle;
       this.registro = registro;
       this.compraDetalles = compraDetalles;
       this.kardexArticuloProductos = kardexArticuloProductos;
    }
   
    public Integer getCodAlmacen() {
        return this.codAlmacen;
    }
    
    public void setCodAlmacen(Integer codAlmacen) {
        this.codAlmacen = codAlmacen;
    }
    public String getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(String almacen) {
        this.almacen = almacen;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<CompraDetalle> getCompraDetalles() {
        return this.compraDetalles;
    }
    
    public void setCompraDetalles(Set<CompraDetalle> compraDetalles) {
        this.compraDetalles = compraDetalles;
    }
    public Set<KardexArticuloProducto> getKardexArticuloProductos() {
        return this.kardexArticuloProductos;
    }
    
    public void setKardexArticuloProductos(Set<KardexArticuloProducto> kardexArticuloProductos) {
        this.kardexArticuloProductos = kardexArticuloProductos;
    }




}


