package tablas;
// Generated 17/12/2013 10:15:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer codArea;
     private String area;
     private String detalle;
     private String registro;
     private Set<Personal> personals = new HashSet<Personal>(0);

    public Area() {
    }

	
    public Area(String area, String detalle, String registro) {
        this.area = area;
        this.detalle = detalle;
        this.registro = registro;
    }
    public Area(String area, String detalle, String registro, Set<Personal> personals) {
       this.area = area;
       this.detalle = detalle;
       this.registro = registro;
       this.personals = personals;
    }
   
    public Integer getCodArea() {
        return this.codArea;
    }
    
    public void setCodArea(Integer codArea) {
        this.codArea = codArea;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<Personal> getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set<Personal> personals) {
        this.personals = personals;
    }




}


