package tablas;
// Generated 14/05/2014 01:19:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ArticuloProducto generated by hbm2java
 */
public class ArticuloProducto  implements java.io.Serializable {


     private Integer codArticuloProducto;
     private Marca marca;
     private Familia familia;
     private String codReferencia;
     private String descripcion;
     private double precioVenta;
     private int precioVentaRango;
     private String unidadMedida;
     private Boolean usarSerieNumero;
     private Boolean reintegroTributario;
     private String observaciones;
     private String foto;
     private String registro;
     private Set<KardexArticuloProducto> kardexArticuloProductos = new HashSet<KardexArticuloProducto>(0);
     private Set<CompraDetalle> compraDetalles = new HashSet<CompraDetalle>(0);
     private Set<VentasDetalle> ventasDetalles = new HashSet<VentasDetalle>(0);
     private Set<PrecioVenta> precioVentas = new HashSet<PrecioVenta>(0);

    public ArticuloProducto() {
    }

	
    public ArticuloProducto(Marca marca, Familia familia, String descripcion, double precioVenta, int precioVentaRango, String registro) {
        this.marca = marca;
        this.familia = familia;
        this.descripcion = descripcion;
        this.precioVenta = precioVenta;
        this.precioVentaRango = precioVentaRango;
        this.registro = registro;
    }
    public ArticuloProducto(Marca marca, Familia familia, String codReferencia, String descripcion, double precioVenta, int precioVentaRango, String unidadMedida, Boolean usarSerieNumero, Boolean reintegroTributario, String observaciones, String foto, String registro, Set<KardexArticuloProducto> kardexArticuloProductos, Set<CompraDetalle> compraDetalles, Set<VentasDetalle> ventasDetalles, Set<PrecioVenta> precioVentas) {
       this.marca = marca;
       this.familia = familia;
       this.codReferencia = codReferencia;
       this.descripcion = descripcion;
       this.precioVenta = precioVenta;
       this.precioVentaRango = precioVentaRango;
       this.unidadMedida = unidadMedida;
       this.usarSerieNumero = usarSerieNumero;
       this.reintegroTributario = reintegroTributario;
       this.observaciones = observaciones;
       this.foto = foto;
       this.registro = registro;
       this.kardexArticuloProductos = kardexArticuloProductos;
       this.compraDetalles = compraDetalles;
       this.ventasDetalles = ventasDetalles;
       this.precioVentas = precioVentas;
    }
   
    public Integer getCodArticuloProducto() {
        return this.codArticuloProducto;
    }
    
    public void setCodArticuloProducto(Integer codArticuloProducto) {
        this.codArticuloProducto = codArticuloProducto;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public String getCodReferencia() {
        return this.codReferencia;
    }
    
    public void setCodReferencia(String codReferencia) {
        this.codReferencia = codReferencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(double precioVenta) {
        this.precioVenta = precioVenta;
    }
    public int getPrecioVentaRango() {
        return this.precioVentaRango;
    }
    
    public void setPrecioVentaRango(int precioVentaRango) {
        this.precioVentaRango = precioVentaRango;
    }
    public String getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public Boolean getUsarSerieNumero() {
        return this.usarSerieNumero;
    }
    
    public void setUsarSerieNumero(Boolean usarSerieNumero) {
        this.usarSerieNumero = usarSerieNumero;
    }
    public Boolean getReintegroTributario() {
        return this.reintegroTributario;
    }
    
    public void setReintegroTributario(Boolean reintegroTributario) {
        this.reintegroTributario = reintegroTributario;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<KardexArticuloProducto> getKardexArticuloProductos() {
        return this.kardexArticuloProductos;
    }
    
    public void setKardexArticuloProductos(Set<KardexArticuloProducto> kardexArticuloProductos) {
        this.kardexArticuloProductos = kardexArticuloProductos;
    }
    public Set<CompraDetalle> getCompraDetalles() {
        return this.compraDetalles;
    }
    
    public void setCompraDetalles(Set<CompraDetalle> compraDetalles) {
        this.compraDetalles = compraDetalles;
    }
    public Set<VentasDetalle> getVentasDetalles() {
        return this.ventasDetalles;
    }
    
    public void setVentasDetalles(Set<VentasDetalle> ventasDetalles) {
        this.ventasDetalles = ventasDetalles;
    }
    public Set<PrecioVenta> getPrecioVentas() {
        return this.precioVentas;
    }
    
    public void setPrecioVentas(Set<PrecioVenta> precioVentas) {
        this.precioVentas = precioVentas;
    }




}


