package tablas;
// Generated 29/04/2014 10:30:26 AM by Hibernate Tools 3.6.0



/**
 * CobranzaDetalle generated by hbm2java
 */
public class CobranzaDetalle  implements java.io.Serializable {


     private Integer codCobranzaDetalle;
     private Cobranza cobranza;
     private VentaCreditoLetra ventaCreditoLetra;
     private Double importe;
     private String observacion;
     private String registro;

    public CobranzaDetalle() {
    }

	
    public CobranzaDetalle(Cobranza cobranza, VentaCreditoLetra ventaCreditoLetra, String registro) {
        this.cobranza = cobranza;
        this.ventaCreditoLetra = ventaCreditoLetra;
        this.registro = registro;
    }
    public CobranzaDetalle(Cobranza cobranza, VentaCreditoLetra ventaCreditoLetra, Double importe, String observacion, String registro) {
       this.cobranza = cobranza;
       this.ventaCreditoLetra = ventaCreditoLetra;
       this.importe = importe;
       this.observacion = observacion;
       this.registro = registro;
    }
   
    public Integer getCodCobranzaDetalle() {
        return this.codCobranzaDetalle;
    }
    
    public void setCodCobranzaDetalle(Integer codCobranzaDetalle) {
        this.codCobranzaDetalle = codCobranzaDetalle;
    }
    public Cobranza getCobranza() {
        return this.cobranza;
    }
    
    public void setCobranza(Cobranza cobranza) {
        this.cobranza = cobranza;
    }
    public VentaCreditoLetra getVentaCreditoLetra() {
        return this.ventaCreditoLetra;
    }
    
    public void setVentaCreditoLetra(VentaCreditoLetra ventaCreditoLetra) {
        this.ventaCreditoLetra = ventaCreditoLetra;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


