package tablas;
// Generated 14/05/2014 01:19:00 PM by Hibernate Tools 3.6.0



/**
 * CompraSerieNumero generated by hbm2java
 */
public class CompraSerieNumero  implements java.io.Serializable {


     private Integer codCompraSerieNumero;
     private CompraDetalle compraDetalle;
     private String serieNumero;
     private String observacion;
     private String registro;

    public CompraSerieNumero() {
    }

	
    public CompraSerieNumero(CompraDetalle compraDetalle, String registro) {
        this.compraDetalle = compraDetalle;
        this.registro = registro;
    }
    public CompraSerieNumero(CompraDetalle compraDetalle, String serieNumero, String observacion, String registro) {
       this.compraDetalle = compraDetalle;
       this.serieNumero = serieNumero;
       this.observacion = observacion;
       this.registro = registro;
    }
   
    public Integer getCodCompraSerieNumero() {
        return this.codCompraSerieNumero;
    }
    
    public void setCodCompraSerieNumero(Integer codCompraSerieNumero) {
        this.codCompraSerieNumero = codCompraSerieNumero;
    }
    public CompraDetalle getCompraDetalle() {
        return this.compraDetalle;
    }
    
    public void setCompraDetalle(CompraDetalle compraDetalle) {
        this.compraDetalle = compraDetalle;
    }
    public String getSerieNumero() {
        return this.serieNumero;
    }
    
    public void setSerieNumero(String serieNumero) {
        this.serieNumero = serieNumero;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


