package tablas;
// Generated 17/12/2013 10:15:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CompraDetalle generated by hbm2java
 */
public class CompraDetalle  implements java.io.Serializable {


     private Integer codCompraDetalle;
     private ArticuloProducto articuloProducto;
     private Compra compra;
     private Almacen almacen;
     private int cantidad;
     private String descripcion;
     private Double precioUnitario;
     private Double precioTotal;
     private Integer item;
     private String detalle;
     private String registro;
     private Set<CompraSerieNumero> compraSerieNumeros = new HashSet<CompraSerieNumero>(0);
     private Set<DetalleDescripcion> detalleDescripcions = new HashSet<DetalleDescripcion>(0);

    public CompraDetalle() {
    }

	
    public CompraDetalle(ArticuloProducto articuloProducto, Compra compra, Almacen almacen, int cantidad, String registro) {
        this.articuloProducto = articuloProducto;
        this.compra = compra;
        this.almacen = almacen;
        this.cantidad = cantidad;
        this.registro = registro;
    }
    public CompraDetalle(ArticuloProducto articuloProducto, Compra compra, Almacen almacen, int cantidad, String descripcion, Double precioUnitario, Double precioTotal, Integer item, String detalle, String registro, Set<CompraSerieNumero> compraSerieNumeros, Set<DetalleDescripcion> detalleDescripcions) {
       this.articuloProducto = articuloProducto;
       this.compra = compra;
       this.almacen = almacen;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
       this.precioUnitario = precioUnitario;
       this.precioTotal = precioTotal;
       this.item = item;
       this.detalle = detalle;
       this.registro = registro;
       this.compraSerieNumeros = compraSerieNumeros;
       this.detalleDescripcions = detalleDescripcions;
    }
   
    public Integer getCodCompraDetalle() {
        return this.codCompraDetalle;
    }
    
    public void setCodCompraDetalle(Integer codCompraDetalle) {
        this.codCompraDetalle = codCompraDetalle;
    }
    public ArticuloProducto getArticuloProducto() {
        return this.articuloProducto;
    }
    
    public void setArticuloProducto(ArticuloProducto articuloProducto) {
        this.articuloProducto = articuloProducto;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Double getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(Double precioTotal) {
        this.precioTotal = precioTotal;
    }
    public Integer getItem() {
        return this.item;
    }
    
    public void setItem(Integer item) {
        this.item = item;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<CompraSerieNumero> getCompraSerieNumeros() {
        return this.compraSerieNumeros;
    }
    
    public void setCompraSerieNumeros(Set<CompraSerieNumero> compraSerieNumeros) {
        this.compraSerieNumeros = compraSerieNumeros;
    }
    public Set<DetalleDescripcion> getDetalleDescripcions() {
        return this.detalleDescripcions;
    }
    
    public void setDetalleDescripcions(Set<DetalleDescripcion> detalleDescripcions) {
        this.detalleDescripcions = detalleDescripcions;
    }




}


