package tablas;
// Generated 17/12/2013 10:15:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DatosCliente generated by hbm2java
 */
public class DatosCliente  implements java.io.Serializable {


     private Integer codDatosCliente;
     private EmpresaConvenio empresaConvenio;
     private Persona persona;
     private Integer tipoCliente;
     private String centroTrabajo;
     private String telefono;
     private int tipo;
     private Integer condicion;
     private double creditoMax;
     private double saldoFavor;
     private String observaciones;
     private int codCobrador;
     private String registro;
     private Set<DocumentoNotificacion> documentoNotificacions = new HashSet<DocumentoNotificacion>(0);

    public DatosCliente() {
    }

	
    public DatosCliente(EmpresaConvenio empresaConvenio, Persona persona, int tipo, double creditoMax, double saldoFavor, int codCobrador, String registro) {
        this.empresaConvenio = empresaConvenio;
        this.persona = persona;
        this.tipo = tipo;
        this.creditoMax = creditoMax;
        this.saldoFavor = saldoFavor;
        this.codCobrador = codCobrador;
        this.registro = registro;
    }
    public DatosCliente(EmpresaConvenio empresaConvenio, Persona persona, Integer tipoCliente, String centroTrabajo, String telefono, int tipo, Integer condicion, double creditoMax, double saldoFavor, String observaciones, int codCobrador, String registro, Set<DocumentoNotificacion> documentoNotificacions) {
       this.empresaConvenio = empresaConvenio;
       this.persona = persona;
       this.tipoCliente = tipoCliente;
       this.centroTrabajo = centroTrabajo;
       this.telefono = telefono;
       this.tipo = tipo;
       this.condicion = condicion;
       this.creditoMax = creditoMax;
       this.saldoFavor = saldoFavor;
       this.observaciones = observaciones;
       this.codCobrador = codCobrador;
       this.registro = registro;
       this.documentoNotificacions = documentoNotificacions;
    }
   
    public Integer getCodDatosCliente() {
        return this.codDatosCliente;
    }
    
    public void setCodDatosCliente(Integer codDatosCliente) {
        this.codDatosCliente = codDatosCliente;
    }
    public EmpresaConvenio getEmpresaConvenio() {
        return this.empresaConvenio;
    }
    
    public void setEmpresaConvenio(EmpresaConvenio empresaConvenio) {
        this.empresaConvenio = empresaConvenio;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Integer getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(Integer tipoCliente) {
        this.tipoCliente = tipoCliente;
    }
    public String getCentroTrabajo() {
        return this.centroTrabajo;
    }
    
    public void setCentroTrabajo(String centroTrabajo) {
        this.centroTrabajo = centroTrabajo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public Integer getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(Integer condicion) {
        this.condicion = condicion;
    }
    public double getCreditoMax() {
        return this.creditoMax;
    }
    
    public void setCreditoMax(double creditoMax) {
        this.creditoMax = creditoMax;
    }
    public double getSaldoFavor() {
        return this.saldoFavor;
    }
    
    public void setSaldoFavor(double saldoFavor) {
        this.saldoFavor = saldoFavor;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public int getCodCobrador() {
        return this.codCobrador;
    }
    
    public void setCodCobrador(int codCobrador) {
        this.codCobrador = codCobrador;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<DocumentoNotificacion> getDocumentoNotificacions() {
        return this.documentoNotificacions;
    }
    
    public void setDocumentoNotificacions(Set<DocumentoNotificacion> documentoNotificacions) {
        this.documentoNotificacions = documentoNotificacions;
    }




}


