package tablas;
// Generated 01/10/2014 04:51:32 PM by Hibernate Tools 3.6.0



/**
 * DatosExtras generated by hbm2java
 */
public class DatosExtras  implements java.io.Serializable {


     private Integer codDatosExtras;
     private String codSeguimiento;
     private String descripcionDato;
     private String letras;
     private String abreviatura;
     private Integer entero;
     private Double decimalDato;
     private String registro;

    public DatosExtras() {
    }

	
    public DatosExtras(String registro) {
        this.registro = registro;
    }
    public DatosExtras(String codSeguimiento, String descripcionDato, String letras, String abreviatura, Integer entero, Double decimalDato, String registro) {
       this.codSeguimiento = codSeguimiento;
       this.descripcionDato = descripcionDato;
       this.letras = letras;
       this.abreviatura = abreviatura;
       this.entero = entero;
       this.decimalDato = decimalDato;
       this.registro = registro;
    }
   
    public Integer getCodDatosExtras() {
        return this.codDatosExtras;
    }
    
    public void setCodDatosExtras(Integer codDatosExtras) {
        this.codDatosExtras = codDatosExtras;
    }
    public String getCodSeguimiento() {
        return this.codSeguimiento;
    }
    
    public void setCodSeguimiento(String codSeguimiento) {
        this.codSeguimiento = codSeguimiento;
    }
    public String getDescripcionDato() {
        return this.descripcionDato;
    }
    
    public void setDescripcionDato(String descripcionDato) {
        this.descripcionDato = descripcionDato;
    }
    public String getLetras() {
        return this.letras;
    }
    
    public void setLetras(String letras) {
        this.letras = letras;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public Integer getEntero() {
        return this.entero;
    }
    
    public void setEntero(Integer entero) {
        this.entero = entero;
    }
    public Double getDecimalDato() {
        return this.decimalDato;
    }
    
    public void setDecimalDato(Double decimalDato) {
        this.decimalDato = decimalDato;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


