package tablas;
// Generated 14/05/2014 01:19:00 PM by Hibernate Tools 3.6.0



/**
 * DetalleDescripcion generated by hbm2java
 */
public class DetalleDescripcion  implements java.io.Serializable {


     private Integer codDetalleDescripcion;
     private CompraDetalle compraDetalle;
     private String nombreDescripcion;
     private String detalleDescripcion;
     private Boolean estado;
     private String registro;

    public DetalleDescripcion() {
    }

	
    public DetalleDescripcion(CompraDetalle compraDetalle, String registro) {
        this.compraDetalle = compraDetalle;
        this.registro = registro;
    }
    public DetalleDescripcion(CompraDetalle compraDetalle, String nombreDescripcion, String detalleDescripcion, Boolean estado, String registro) {
       this.compraDetalle = compraDetalle;
       this.nombreDescripcion = nombreDescripcion;
       this.detalleDescripcion = detalleDescripcion;
       this.estado = estado;
       this.registro = registro;
    }
   
    public Integer getCodDetalleDescripcion() {
        return this.codDetalleDescripcion;
    }
    
    public void setCodDetalleDescripcion(Integer codDetalleDescripcion) {
        this.codDetalleDescripcion = codDetalleDescripcion;
    }
    public CompraDetalle getCompraDetalle() {
        return this.compraDetalle;
    }
    
    public void setCompraDetalle(CompraDetalle compraDetalle) {
        this.compraDetalle = compraDetalle;
    }
    public String getNombreDescripcion() {
        return this.nombreDescripcion;
    }
    
    public void setNombreDescripcion(String nombreDescripcion) {
        this.nombreDescripcion = nombreDescripcion;
    }
    public String getDetalleDescripcion() {
        return this.detalleDescripcion;
    }
    
    public void setDetalleDescripcion(String detalleDescripcion) {
        this.detalleDescripcion = detalleDescripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


