package tablas;
// Generated 17/12/2013 10:15:59 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DocumentoNotificacion generated by hbm2java
 */
public class DocumentoNotificacion  implements java.io.Serializable {


     private Integer codDocumentoNotificacion;
     private DatosCliente datosCliente;
     private Date fech1;
     private Date fech2;
     private Date fech3;
     private String varchar1;
     private String varchar2;
     private String text1;
     private String text2;
     private String text3;
     private String registro;

    public DocumentoNotificacion() {
    }

	
    public DocumentoNotificacion(DatosCliente datosCliente, String registro) {
        this.datosCliente = datosCliente;
        this.registro = registro;
    }
    public DocumentoNotificacion(DatosCliente datosCliente, Date fech1, Date fech2, Date fech3, String varchar1, String varchar2, String text1, String text2, String text3, String registro) {
       this.datosCliente = datosCliente;
       this.fech1 = fech1;
       this.fech2 = fech2;
       this.fech3 = fech3;
       this.varchar1 = varchar1;
       this.varchar2 = varchar2;
       this.text1 = text1;
       this.text2 = text2;
       this.text3 = text3;
       this.registro = registro;
    }
   
    public Integer getCodDocumentoNotificacion() {
        return this.codDocumentoNotificacion;
    }
    
    public void setCodDocumentoNotificacion(Integer codDocumentoNotificacion) {
        this.codDocumentoNotificacion = codDocumentoNotificacion;
    }
    public DatosCliente getDatosCliente() {
        return this.datosCliente;
    }
    
    public void setDatosCliente(DatosCliente datosCliente) {
        this.datosCliente = datosCliente;
    }
    public Date getFech1() {
        return this.fech1;
    }
    
    public void setFech1(Date fech1) {
        this.fech1 = fech1;
    }
    public Date getFech2() {
        return this.fech2;
    }
    
    public void setFech2(Date fech2) {
        this.fech2 = fech2;
    }
    public Date getFech3() {
        return this.fech3;
    }
    
    public void setFech3(Date fech3) {
        this.fech3 = fech3;
    }
    public String getVarchar1() {
        return this.varchar1;
    }
    
    public void setVarchar1(String varchar1) {
        this.varchar1 = varchar1;
    }
    public String getVarchar2() {
        return this.varchar2;
    }
    
    public void setVarchar2(String varchar2) {
        this.varchar2 = varchar2;
    }
    public String getText1() {
        return this.text1;
    }
    
    public void setText1(String text1) {
        this.text1 = text1;
    }
    public String getText2() {
        return this.text2;
    }
    
    public void setText2(String text2) {
        this.text2 = text2;
    }
    public String getText3() {
        return this.text3;
    }
    
    public void setText3(String text3) {
        this.text3 = text3;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


