package tablas;
// Generated 14/05/2014 01:19:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * EmpresaConvenio generated by hbm2java
 */
public class EmpresaConvenio  implements java.io.Serializable {


     private Integer codEmpresaConvenio;
     private String nombre;
     private String abreviatura;
     private String codCobranza;
     private boolean interesAsigando;
     private boolean interesAutomatico;
     private String registro;
     private Set<DatosCliente> datosClientes = new HashSet<DatosCliente>(0);
     private Set<OtrosCC> otrosCCs = new HashSet<OtrosCC>(0);

    public EmpresaConvenio() {
    }

	
    public EmpresaConvenio(String nombre, String codCobranza, boolean interesAsigando, boolean interesAutomatico, String registro) {
        this.nombre = nombre;
        this.codCobranza = codCobranza;
        this.interesAsigando = interesAsigando;
        this.interesAutomatico = interesAutomatico;
        this.registro = registro;
    }
    public EmpresaConvenio(String nombre, String abreviatura, String codCobranza, boolean interesAsigando, boolean interesAutomatico, String registro, Set<DatosCliente> datosClientes, Set<OtrosCC> otrosCCs) {
       this.nombre = nombre;
       this.abreviatura = abreviatura;
       this.codCobranza = codCobranza;
       this.interesAsigando = interesAsigando;
       this.interesAutomatico = interesAutomatico;
       this.registro = registro;
       this.datosClientes = datosClientes;
       this.otrosCCs = otrosCCs;
    }
   
    public Integer getCodEmpresaConvenio() {
        return this.codEmpresaConvenio;
    }
    
    public void setCodEmpresaConvenio(Integer codEmpresaConvenio) {
        this.codEmpresaConvenio = codEmpresaConvenio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public String getCodCobranza() {
        return this.codCobranza;
    }
    
    public void setCodCobranza(String codCobranza) {
        this.codCobranza = codCobranza;
    }
    public boolean isInteresAsigando() {
        return this.interesAsigando;
    }
    
    public void setInteresAsigando(boolean interesAsigando) {
        this.interesAsigando = interesAsigando;
    }
    public boolean isInteresAutomatico() {
        return this.interesAutomatico;
    }
    
    public void setInteresAutomatico(boolean interesAutomatico) {
        this.interesAutomatico = interesAutomatico;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<DatosCliente> getDatosClientes() {
        return this.datosClientes;
    }
    
    public void setDatosClientes(Set<DatosCliente> datosClientes) {
        this.datosClientes = datosClientes;
    }
    public Set<OtrosCC> getOtrosCCs() {
        return this.otrosCCs;
    }
    
    public void setOtrosCCs(Set<OtrosCC> otrosCCs) {
        this.otrosCCs = otrosCCs;
    }




}


