package tablas;
// Generated 17/12/2013 10:15:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Familia generated by hbm2java
 */
public class Familia  implements java.io.Serializable {


     private Integer codFamilia;
     private String familia;
     private String observacion;
     private String registro;
     private Set<ArticuloProducto> articuloProductos = new HashSet<ArticuloProducto>(0);

    public Familia() {
    }

	
    public Familia(String registro) {
        this.registro = registro;
    }
    public Familia(String familia, String observacion, String registro, Set<ArticuloProducto> articuloProductos) {
       this.familia = familia;
       this.observacion = observacion;
       this.registro = registro;
       this.articuloProductos = articuloProductos;
    }
   
    public Integer getCodFamilia() {
        return this.codFamilia;
    }
    
    public void setCodFamilia(Integer codFamilia) {
        this.codFamilia = codFamilia;
    }
    public String getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(String familia) {
        this.familia = familia;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<ArticuloProducto> getArticuloProductos() {
        return this.articuloProductos;
    }
    
    public void setArticuloProductos(Set<ArticuloProducto> articuloProductos) {
        this.articuloProductos = articuloProductos;
    }




}


