package tablas;
// Generated 10/04/2014 10:20:20 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer codProveedor;
     private String ruc;
     private String razonSocial;
     private String direccion;
     private String telefono;
     private String email;
     private String paginaWeb;
     private String observaciones;
     private String logo;
     private String registro;
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Proveedor() {
    }

	
    public Proveedor(String ruc, String razonSocial, String direccion, String telefono, String registro) {
        this.ruc = ruc;
        this.razonSocial = razonSocial;
        this.direccion = direccion;
        this.telefono = telefono;
        this.registro = registro;
    }
    public Proveedor(String ruc, String razonSocial, String direccion, String telefono, String email, String paginaWeb, String observaciones, String logo, String registro, Set<Compra> compras) {
       this.ruc = ruc;
       this.razonSocial = razonSocial;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.paginaWeb = paginaWeb;
       this.observaciones = observaciones;
       this.logo = logo;
       this.registro = registro;
       this.compras = compras;
    }
   
    public Integer getCodProveedor() {
        return this.codProveedor;
    }
    
    public void setCodProveedor(Integer codProveedor) {
        this.codProveedor = codProveedor;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


