package tablas;
// Generated 01/10/2014 04:51:32 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento  implements java.io.Serializable {


     private Integer codTipoDocumento;
     private String tipoDocumeto;
     private String detalle;
     private String registro;
     private Set<TramiteDocumentario> tramiteDocumentarios = new HashSet<TramiteDocumentario>(0);

    public TipoDocumento() {
    }

	
    public TipoDocumento(String tipoDocumeto, String registro) {
        this.tipoDocumeto = tipoDocumeto;
        this.registro = registro;
    }
    public TipoDocumento(String tipoDocumeto, String detalle, String registro, Set<TramiteDocumentario> tramiteDocumentarios) {
       this.tipoDocumeto = tipoDocumeto;
       this.detalle = detalle;
       this.registro = registro;
       this.tramiteDocumentarios = tramiteDocumentarios;
    }
   
    public Integer getCodTipoDocumento() {
        return this.codTipoDocumento;
    }
    
    public void setCodTipoDocumento(Integer codTipoDocumento) {
        this.codTipoDocumento = codTipoDocumento;
    }
    public String getTipoDocumeto() {
        return this.tipoDocumeto;
    }
    
    public void setTipoDocumeto(String tipoDocumeto) {
        this.tipoDocumeto = tipoDocumeto;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<TramiteDocumentario> getTramiteDocumentarios() {
        return this.tramiteDocumentarios;
    }
    
    public void setTramiteDocumentarios(Set<TramiteDocumentario> tramiteDocumentarios) {
        this.tramiteDocumentarios = tramiteDocumentarios;
    }




}


