package tablas;
// Generated 10/04/2014 10:20:20 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TramiteDocumentario generated by hbm2java
 */
public class TramiteDocumentario  implements java.io.Serializable {


     private Integer codTramiteDocumentario;
     private TipoDocumento tipoDocumento;
     private Ventas ventas;
     private EstadoDocumento estadoDocumento;
     private Date fechaSolicitud;
     private Date fechaProbableEntrega;
     private Date fechaEntrega;
     private String detalle;
     private String registro;

    public TramiteDocumentario() {
    }

	
    public TramiteDocumentario(TipoDocumento tipoDocumento, Ventas ventas, EstadoDocumento estadoDocumento, Date fechaSolicitud, Date fechaProbableEntrega, Date fechaEntrega, String registro) {
        this.tipoDocumento = tipoDocumento;
        this.ventas = ventas;
        this.estadoDocumento = estadoDocumento;
        this.fechaSolicitud = fechaSolicitud;
        this.fechaProbableEntrega = fechaProbableEntrega;
        this.fechaEntrega = fechaEntrega;
        this.registro = registro;
    }
    public TramiteDocumentario(TipoDocumento tipoDocumento, Ventas ventas, EstadoDocumento estadoDocumento, Date fechaSolicitud, Date fechaProbableEntrega, Date fechaEntrega, String detalle, String registro) {
       this.tipoDocumento = tipoDocumento;
       this.ventas = ventas;
       this.estadoDocumento = estadoDocumento;
       this.fechaSolicitud = fechaSolicitud;
       this.fechaProbableEntrega = fechaProbableEntrega;
       this.fechaEntrega = fechaEntrega;
       this.detalle = detalle;
       this.registro = registro;
    }
   
    public Integer getCodTramiteDocumentario() {
        return this.codTramiteDocumentario;
    }
    
    public void setCodTramiteDocumentario(Integer codTramiteDocumentario) {
        this.codTramiteDocumentario = codTramiteDocumentario;
    }
    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public EstadoDocumento getEstadoDocumento() {
        return this.estadoDocumento;
    }
    
    public void setEstadoDocumento(EstadoDocumento estadoDocumento) {
        this.estadoDocumento = estadoDocumento;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    public Date getFechaProbableEntrega() {
        return this.fechaProbableEntrega;
    }
    
    public void setFechaProbableEntrega(Date fechaProbableEntrega) {
        this.fechaProbableEntrega = fechaProbableEntrega;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


