package tablas;
// Generated 14/05/2014 01:19:00 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VentaCredito generated by hbm2java
 */
public class VentaCredito  implements java.io.Serializable {


     private Integer codVentaCredito;
     private Ventas ventas;
     private int personaCodGarante;
     private Boolean estado;
     private String duracion;
     private double montoInicial;
     private Date fechaInicial;
     private Integer cantidadLetras;
     private Double montoLetra;
     private Date fechaVencimientoLetra;
     private String registro;
     private Set<VentaCreditoLetra> ventaCreditoLetras = new HashSet<VentaCreditoLetra>(0);

    public VentaCredito() {
    }

	
    public VentaCredito(Ventas ventas, int personaCodGarante, double montoInicial, String registro) {
        this.ventas = ventas;
        this.personaCodGarante = personaCodGarante;
        this.montoInicial = montoInicial;
        this.registro = registro;
    }
    public VentaCredito(Ventas ventas, int personaCodGarante, Boolean estado, String duracion, double montoInicial, Date fechaInicial, Integer cantidadLetras, Double montoLetra, Date fechaVencimientoLetra, String registro, Set<VentaCreditoLetra> ventaCreditoLetras) {
       this.ventas = ventas;
       this.personaCodGarante = personaCodGarante;
       this.estado = estado;
       this.duracion = duracion;
       this.montoInicial = montoInicial;
       this.fechaInicial = fechaInicial;
       this.cantidadLetras = cantidadLetras;
       this.montoLetra = montoLetra;
       this.fechaVencimientoLetra = fechaVencimientoLetra;
       this.registro = registro;
       this.ventaCreditoLetras = ventaCreditoLetras;
    }
   
    public Integer getCodVentaCredito() {
        return this.codVentaCredito;
    }
    
    public void setCodVentaCredito(Integer codVentaCredito) {
        this.codVentaCredito = codVentaCredito;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public int getPersonaCodGarante() {
        return this.personaCodGarante;
    }
    
    public void setPersonaCodGarante(int personaCodGarante) {
        this.personaCodGarante = personaCodGarante;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public double getMontoInicial() {
        return this.montoInicial;
    }
    
    public void setMontoInicial(double montoInicial) {
        this.montoInicial = montoInicial;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Integer getCantidadLetras() {
        return this.cantidadLetras;
    }
    
    public void setCantidadLetras(Integer cantidadLetras) {
        this.cantidadLetras = cantidadLetras;
    }
    public Double getMontoLetra() {
        return this.montoLetra;
    }
    
    public void setMontoLetra(Double montoLetra) {
        this.montoLetra = montoLetra;
    }
    public Date getFechaVencimientoLetra() {
        return this.fechaVencimientoLetra;
    }
    
    public void setFechaVencimientoLetra(Date fechaVencimientoLetra) {
        this.fechaVencimientoLetra = fechaVencimientoLetra;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<VentaCreditoLetra> getVentaCreditoLetras() {
        return this.ventaCreditoLetras;
    }
    
    public void setVentaCreditoLetras(Set<VentaCreditoLetra> ventaCreditoLetras) {
        this.ventaCreditoLetras = ventaCreditoLetras;
    }




}


