package tablas;
// Generated 29/04/2014 10:30:26 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Zona generated by hbm2java
 */
public class Zona  implements java.io.Serializable {


     private Integer codZona;
     private String zona;
     private String descripcion;
     private String registro;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Zona() {
    }

	
    public Zona(String zona, String registro) {
        this.zona = zona;
        this.registro = registro;
    }
    public Zona(String zona, String descripcion, String registro, Set<Persona> personas) {
       this.zona = zona;
       this.descripcion = descripcion;
       this.registro = registro;
       this.personas = personas;
    }
   
    public Integer getCodZona() {
        return this.codZona;
    }
    
    public void setCodZona(Integer codZona) {
        this.codZona = codZona;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


